language: php

dist: bionic

notifications:
    email: false

php:
    - "7.1"
    - "7.2"
    - "7.3"
    - "7.4"

services: mysql

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_finish: true

env:
  matrix:
    - DEPENDENCIES=""
    - DEPENDENCIES=" --prefer-lowest"
  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest --prefer-dist"
    - DOCS_BUILD_BRANCH="master-schema_documentation_account-OXDEV-3979"
    - GITHUB_PAGES_BRANCH="schema"

install:
    - travis_retry composer update $DEFAULT_COMPOSER_FLAGS $DEPENDENCIES

script:
    - composer test:syntax
    - composer test:lint
    - composer test:unit
    - composer test:infection
    - if [ $(php -r "echo PHP_MAJOR_VERSION . PHP_MINOR_VERSION;") == "74" -a "$DEPENDENCIES" == "" ]; then composer test:static; fi;

after_success:
    - sudo chmod +775 schema.sh
    - ./schema.sh

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: ./docs/_static/schema
    target_branch: $GITHUB_PAGES_BRANCH
    on:
        branch: $DOCS_BUILD_BRANCH
        condition: $TRAVIS_PHP_VERSION = "7.4" && $DEPENDENCIES = ""
