language: php

dist: bionic

notifications:
    email: false

php:
    - "7.1"
    - "7.2"
    - "7.3"
    - "7.4snapshot"

matrix:
    fast_finish: true

before_script:
    - composer install

script:
    - composer test:syntax
    - composer test:lint
