language: php

dist: bionic

notifications:
    email: false

php:
    - "7.4"

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_finish: true

env:
  global:
    - DEPENDENCIES=""
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest --prefer-dist"

install:
    - travis_retry composer update $DEFAULT_COMPOSER_FLAGS $DEPENDENCIES

script: skip

before_deploy:
    - sudo chmod +775 deploy.sh
    - ./deploy.sh

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: ./docs/_static/schema
    target_branch: schema
    on:
        branch: master
        condition: $TRAVIS_PHP_VERSION = "7.4" && $DEPENDENCIES = ""
