language: php

dist: bionic

notifications:
    email: false

php:
    - "7.1"
    - "7.2"
    - "7.3"
    - "7.4"
    - "nightly"

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_finish: true
    allow_failures:
        - php: "nightly"

before_script:
    - composer install --prefer-dist

script:
    - composer test:syntax
    - composer test:lint
    - composer test:static
    - composer test:unit
