language: php

dist: bionic

notifications:
    email: false

php:
    - "7.1"
    - "7.2"
    - "7.3"
    - "7.4"

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_finish: true

env:
  matrix:
    - DEPENDENCIES=""
    - DEPENDENCIES=" --prefer-lowest"
  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest --prefer-dist"

install:
    - travis_retry composer update $DEFAULT_COMPOSER_FLAGS $DEPENDENCIES

script:
    - composer test:syntax
    - composer test:lint
    - composer test:lint-fixer
    - composer test:static
    - composer test:unit
    - composer test:infection
