language: php

dist: bionic

notifications:
    email: false

php:
    - "7.1"
    - "7.2"
    - "7.3"
    - "7.4"

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_finish: true

install:
    - travis_retry composer install --prefer-dist --no-interaction

script:
    - composer test:syntax
    - composer test:lint
    - composer test:lint-fixer
    - composer test:static
    - composer test:unit
    - composer test:infection
