services:

  _defaults:
    public: false
    autowire: true

  OxidEsales\Eshop\Core\PasswordSaltGenerator:
    class: OxidEsales\Eshop\Core\PasswordSaltGenerator

  OxidEsales\Eshop\Core\OpenSSLFunctionalityChecker:
    class: OxidEsales\Eshop\Core\OpenSSLFunctionalityChecker

  OxidEsales\GraphQl\Framework\AppContext:
    factory: ['OxidEsales\GraphQl\Framework\AppContext', 'createAppContext']
    class: OxidEsales\GraphQl\Framework\AppContext

  OxidEsales\GraphQl\Framework\GraphQlQueryHandlerInterface:
    class: OxidEsales\GraphQl\Framework\GraphQlQueryHandler
    public: true

  OxidEsales\GraphQl\Framework\ErrorCodeProviderInterface:
    class: OxidEsales\GraphQl\Framework\ErrorCodeProvider

  OxidEsales\GraphQl\Framework\RequestReaderInterface:
    class: OxidEsales\GraphQl\Framework\RequestReader

  OxidEsales\GraphQl\Framework\ResponseWriterInterface:
    class: OxidEsales\GraphQl\Framework\ResponseWriter

  OxidEsales\GraphQl\Framework\GenericFieldResolverInterface:
    class: OxidEsales\GraphQl\Framework\GenericFieldResolver

  OxidEsales\GraphQl\Dao\UserDaoInterface:
    class: OxidEsales\GraphQl\Dao\UserDao

  OxidEsales\GraphQl\Service\KeyRegistryInterface:
    class: OxidEsales\GraphQl\Service\KeyRegistry
    public: true

  OxidEsales\GraphQl\Service\EnvironmentServiceInterface:
    class: OxidEsales\GraphQl\Service\EnvironmentService

  OxidEsales\GraphQl\Service\AuthenticationServiceInterface:
    class: OxidEsales\GraphQl\Service\AuthenticationService

  OxidEsales\GraphQl\Service\PermissionsServiceInterface:
    class: OxidEsales\GraphQl\Service\PermissionsService
    arguments: [!tagged graphql_permissions_provider]

  OxidEsales\GraphQl\Service\LoginPermissionsProvider:
    class: OxidEsales\GraphQl\Service\PermissionsProvider
    calls:
      - ['addPermission', ['anonymous', 'mayreaddata']]
      - ['addPermission', ['customer', 'mayreaddata']]
      - ['addPermission', ['admin', 'mayreaddata']]
      - ['addPermission', ['shopadmin', 'mayreaddata']]
    tags: ['graphql_permissions_provider']

  OxidEsales\GraphQl\Service\UserPermissionsProvider:
    class: OxidEsales\GraphQl\Service\PermissionsProvider
    calls:
      - ['addPermission', ['anonymous', 'maycreatecustomer']]
      - ['addPermission', ['customer', 'mayupdateself']]
      - ['addPermission', ['customer', 'maygetself']]
      - ['addPermission', ['shopadmin', 'maycreateanyuser']]
      - ['addPermission', ['shopadmin', 'maygetshopuser']]
      - ['addPermission', ['admin', 'maycreateanyuser']]
      - ['addPermission', ['admin', 'maygetanyuser']]
      - ['addPermission', ['admin', 'maycreateuserforothershop']]
      - ['addPermission', ['admin', 'mayupdateanyuser']]
    tags: ['graphql_permissions_provider']

  OxidEsales\GraphQl\Utility\LegacyWrapperInterface:
    class: OxidEsales\GraphQl\Utility\LegacyWrapper

  OxidEsales\GraphQl\Controllers\:
    resource: 'src/Controllers/*'
    public: true

  OxidEsales\GraphQl\Framework\NamespaceMapper:
    class: OxidEsales\GraphQl\Framework\NamespaceMapper
    tags: ['graphql_namespace_mapper']

  OxidEsales\GraphQl\Framework\SchemaFactoryInterface:
    class: OxidEsales\GraphQl\Framework\SchemaFactory
    arguments:
      $namespaceMappers: !tagged graphql_namespace_mapper
