services:

  _defaults:
    public: false
    autowire: true

  OxidEsales\Eshop\Core\PasswordSaltGenerator:
    class: OxidEsales\Eshop\Core\PasswordSaltGenerator

  OxidEsales\Eshop\Core\OpenSSLFunctionalityChecker:
    class: OxidEsales\Eshop\Core\OpenSSLFunctionalityChecker

  OxidEsales\GraphQl\Framework\ModuleSetup:
    class: OxidEsales\GraphQl\Framework\ModuleSetup
    public: true

  OxidEsales\GraphQl\Dao\UserDaoInterface:
    class: OxidEsales\GraphQl\Dao\UserDao

  OxidEsales\GraphQl\Dao\TokenDaoInterface:
    class: OxidEsales\GraphQl\Dao\TokenDao

  OxidEsales\GraphQl\Service\KeyRegistryInterface:
    class: OxidEsales\GraphQl\Service\KeyRegistry

  OxidEsales\GraphQl\Service\EnvironmentServiceInterface:
    class: OxidEsales\GraphQl\Service\EnvironmentService

  OxidEsales\GraphQl\Service\PasswordEncoderInterface:
    class: OxidEsales\GraphQl\Service\PasswordEncoder

  OxidEsales\GraphQl\Service\AuthenticationServiceInterface:
    class: OxidEsales\GraphQl\Service\AuthenticationService

  OxidEsales\GraphQl\Type\LoginType:
    class: OxidEsales\GraphQl\Type\LoginType
    tags: ['graphql_query_type']

  query_type_factory:
    class: OxidEsales\GraphQl\Framework\TypeFactory
    arguments: ['OxidEsales\GraphQl\Type\Query']

  mutation_type_factory:
    class: OxidEsales\GraphQl\Framework\TypeFactory
    arguments: ['OxidEsales\GraphQl\Type\Mutation']

  OxidProfessionalServices\GraphQl\Core\Framework\SchemaFactoryInterface:
    class: OxidEsales\GraphQl\Framework\SchemaFactory
    arguments: ['@query_type_factory', '@mutation_type_factory']
    public: true
