services:

  _defaults:
    public: false
    autowire: true

  OxidEsales\Eshop\Core\PasswordSaltGenerator:
    class: OxidEsales\Eshop\Core\PasswordSaltGenerator

  OxidEsales\Eshop\Core\OpenSSLFunctionalityChecker:
    class: OxidEsales\Eshop\Core\OpenSSLFunctionalityChecker

  OxidEsales\GraphQL\Framework\ModuleSetup:
    class: OxidEsales\GraphQL\Framework\ModuleSetup
    public: true

  OxidEsales\GraphQL\Framework\AppContext:
    factory: ['OxidEsales\GraphQL\Framework\AppContext', 'createAppContext']
    class: OxidEsales\GraphQL\Framework\AppContext

  OxidEsales\GraphQL\Framework\GraphQLQueryHandlerInterface:
    class: OxidEsales\GraphQL\Framework\GraphQLQueryHandler
    public: true

  OxidEsales\GraphQL\Framework\ErrorCodeProviderInterface:
    class: OxidEsales\GraphQL\Framework\ErrorCodeProvider

  OxidEsales\GraphQL\Framework\RequestReaderInterface:
    class: OxidEsales\GraphQL\Framework\RequestReader

  OxidEsales\GraphQL\Framework\ResponseWriterInterface:
    class: OxidEsales\GraphQL\Framework\ResponseWriter

  OxidEsales\GraphQL\Dao\UserDaoInterface:
    class: OxidEsales\GraphQL\Dao\UserDao

  OxidEsales\GraphQL\Service\KeyRegistryInterface:
    class: OxidEsales\GraphQL\Service\KeyRegistry
    public: true

  OxidEsales\GraphQL\Service\EnvironmentServiceInterface:
    class: OxidEsales\GraphQL\Service\EnvironmentService

  OxidEsales\GraphQL\Service\AuthenticationServiceInterface:
    class: OxidEsales\GraphQL\Service\AuthenticationService

  OxidEsales\GraphQL\Service\PermissionsServiceInterface:
    class: OxidEsales\GraphQL\Service\PermissionsService
    arguments: [!tagged graphql_permissions_provider]

  OxidEsales\GraphQL\Service\LoginPermissionsProvider:
    class: OxidEsales\GraphQL\Service\PermissionsProvider
    calls:
      - ['addPermission', ['anonymous', 'mayreaddata']]
      - ['addPermission', ['customer', 'mayreaddata']]
      - ['addPermission', ['admin', 'mayreaddata']]
      - ['addPermission', ['shopadmin', 'mayreaddata']]
    tags: ['graphql_permissions_provider']

  OxidEsales\GraphQL\Service\UserPermissionsProvider:
    class: OxidEsales\GraphQL\Service\PermissionsProvider
    calls:
      - ['addPermission', ['anonymous', 'maycreatecustomer']]
      - ['addPermission', ['customer', 'mayupdateself']]
      - ['addPermission', ['customer', 'maygetself']]
      - ['addPermission', ['shopadmin', 'maycreateanyuser']]
      - ['addPermission', ['shopadmin', 'maygetshopuser']]
      - ['addPermission', ['admin', 'maycreateanyuser']]
      - ['addPermission', ['admin', 'maygetanyuser']]
      - ['addPermission', ['admin', 'maycreateuserforothershop']]
      - ['addPermission', ['admin', 'mayupdateanyuser']]
    tags: ['graphql_permissions_provider']

  OxidEsales\GraphQL\Controllers\:
    resource: 'src/Controllers/*'
    public: true

  OxidEsales\GraphQL\Framework\NamespaceMapper:
    class: OxidEsales\GraphQL\Framework\NamespaceMapper
    tags: ['graphql_namespace_mapper']

  OxidEsales\GraphQL\Framework\SchemaFactoryInterface:
    class: OxidEsales\GraphQL\Framework\SchemaFactory
    arguments:
      $namespaceMappers: !tagged graphql_namespace_mapper
