services:

  _defaults:
    public: false
    autowire: true

  OxidEsales\GraphQL\Framework\ModuleSetup:
    class: OxidEsales\GraphQL\Framework\ModuleSetup
    public: true

  OxidEsales\GraphQL\Framework\GraphQLQueryHandlerInterface:
    class: OxidEsales\GraphQL\Framework\GraphQLQueryHandler
    public: true

  OxidEsales\GraphQL\Framework\ErrorCodeProviderInterface:
    class: OxidEsales\GraphQL\Framework\ErrorCodeProvider

  OxidEsales\GraphQL\Framework\RequestReaderInterface:
    class: OxidEsales\GraphQL\Framework\RequestReader

  OxidEsales\GraphQL\Framework\ResponseWriterInterface:
    class: OxidEsales\GraphQL\Framework\ResponseWriter

  OxidEsales\GraphQL\Service\KeyRegistryInterface:
    class: OxidEsales\GraphQL\Service\KeyRegistry
    public: true

  Lcobucci\JWT\Token:
    factory: ['@OxidEsales\GraphQL\Framework\RequestReaderInterface', 'getAuthToken']

  OxidEsales\GraphQL\Service\AuthenticationServiceInterface:
    class: OxidEsales\GraphQL\Service\AuthenticationService
    calls:
      - [setToken, ['@?Lcobucci\JWT\Token']]

  OxidEsales\GraphQL\Service\LegacyServiceInterface:
    class: OxidEsales\GraphQL\Service\LegacyService

  OxidEsales\GraphQL\Service\AuthorizationServiceInterface:
    class: OxidEsales\GraphQL\Service\AuthorizationService
    arguments:
        $permissionProviders: !tagged graphql_permission_provider
    calls:
      - [setToken, ['@?Lcobucci\JWT\Token']]

  OxidEsales\GraphQL\Controller\:
    resource: 'src/Controller/*'
    public: true

  OxidEsales\GraphQL\Service\PermissionProvider:
    class: OxidEsales\GraphQL\Service\PermissionProvider
    tags: ['graphql_permission_provider']

  OxidEsales\GraphQL\Service\NamespaceMapper:
    class: OxidEsales\GraphQL\Service\NamespaceMapper
    tags: ['graphql_namespace_mapper']

  OxidEsales\GraphQL\Framework\SchemaFactoryInterface:
    class: OxidEsales\GraphQL\Framework\SchemaFactory
    arguments:
      $namespaceMappers: !tagged graphql_namespace_mapper
