name: CI

on:
    - push
    - pull_request

env:
    DEFAULT_COMPOSER_FLAGS: --no-interaction --no-ansi --no-progress --no-suggest --prefer-dist

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php:
                    - "7.1"
                    - "7.2"
                    - "7.3"
                    - "7.4"
                env:
                    - DEPENDENCIES=""
                    - DEPENDENCIES=" --prefer-lowest"

        steps:
            - name: Checkout graphql-base
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}

            - name: Downgrade composer
              if: ${{ matrix.php != 7.4 || env.DEPENDENCIES == ' --prefer-lowest' }}
              run: composer self-update --1

            - name: Get composer cache directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Install dependencies
              run: composer update $DEFAULT_COMPOSER_FLAGS $DEPENDENCIES

            - name: Test syntax
              run: composer test:syntax

            - name: Lint
              run: composer test:lint

            - name: Unit Tests
              run: composer test:unit

            - name: Infection
              run: composer test:infection

            - name: Static analysis
              if: ${{ matrix.php == 7.4 && env.DEPENDENCIES == '' }}
              run: composer test:static
